version: '3.2'

services:
  cnc:
    build:
      context: .
      dockerfile: Cnc
    networks:
      network1:
        ipv4_address: 192.168.10.10
      network2:

    command: "mysqld_safe"

  attacker:
    image: alpine
    networks:
      - network1
      - network2
    command: ["sleep", "infinity"]
  
  victim_access:
    image: alpine
    networks:
      - network2
      - network1
    command: ["sleep", "infinity"]

  victim_internal1:
    image: alpine
    networks:
      - network2
      - network1
    command: ["sleep", "infinity"]

  victim_internal2:
    image: alpine
    networks:
      - network2
      - network1
    command: ["sleep", "infinity"]


networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
    internal: true

  network2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
    internal: true
