services:
  cnc:
    container_name: mirai-cnc
    build:
      context: .
      dockerfile: Cnc
    networks:
      network1:
        ipv4_address: 192.168.10.10
      network2:

    command: ["mysqld_safe"]

  attacker:
    container_name: mirai-attacker
    image: alpine
    networks:
      - network1
      - network2
    command: ["sleep", "infinity"]
  
  victim_access:
    container_name: mirai-victim-access
    build:
      context: .
      dockerfile: Victim
    networks:
      - network2
      - network1
    ports:
      - "23:9923"
    command: ["/bin/sh", "-c", "telnetd && sleep infinity"]

  victim_internal1:
    container_name: mirai-victim-internal-1
    build:
      context: .
      dockerfile: Victim
    networks:
      - network2
      - network1
    command: ["/bin/sh", "-c", "telnetd && sleep infinity"]

  victim_internal2:
    container_name: mirai-victim-internal-2
    build:
      context: .
      dockerfile: Victim
    networks:
      - network2
      - network1
    command: ["/bin/sh", "-c", "telnetd && sleep infinity"]


networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
    internal: true

  network2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
    internal: true
