services:
  cnc:
    container_name: mirai-cnc
    build:
      context: .
      dockerfile: Cnc
    networks:
      network2:
        ipv4_address: 192.168.10.10
    ports:
      - "23:9925"
    command: ["mysqld_safe"]

  attacker:
    container_name: mirai-attacker
    image: alpine
    networks:
      - network2
    command: ["sleep", "infinity"]
  
  victim_access:
    container_name: mirai-victim-access
    build:
      context: .
      dockerfile: Victim
    networks:
      network2:
        ipv4_address: 192.168.10.5
    ports:
      - "23:9923"
    command: ["/bin/sh", "-c", "telnetd && sleep infinity"]

  victim_internal1:
    container_name: mirai-victim-internal-1
    build:
      context: .
      dockerfile: Victim
    networks:
      network2:
        ipv4_address: 192.168.10.6
    command: ["/bin/sh", "-c", "telnetd && sleep infinity"]

  victim_internal2:
    container_name: mirai-victim-internal-2
    build:
      context: .
      dockerfile: Victim
    networks:
      network2:
        ipv4_address: 192.168.10.7
    command: ["/bin/sh", "-c", "telnetd && sleep infinity"]

  nginx:
    container_name: attack-me
    image: nginx:latest
    ports:
      - "9999:80"
    volumes: 
      - /var/www/html:/usr/share/nginx/html
    restart: always
    networks:
      - network2

networks:
  network2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
    internal: true
